### ISSUE TITLE
是否可以向 Controller 一样支持多级目录？

### ISSUE THREAD

**Issue by onweer** [liuxiaodong/egg-joi#2]
![image](https://user-images.githubusercontent.com/11755669/34264655-8a626dea-e6ae-11e7-9253-3a96fa66519b.png)

**Comment by liuxiaodong** [comment]
是支持多级目录的，可以参考<a href="https://github.com/liuxiaodong/egg-joi/blob/master/test/fixtures/apps/joi-test/app/router.js">测试代码 </a>
