### ISSUE TITLE
去掉 validate 同时返回 error 和 value

### ISSUE THREAD

**Issue by seekcx** [liuxiaodong/egg-joi#6]
error 的获取应该直接try catch。而不是通过返回。

目前这样，下面这种偷懒技巧就不太好用了。

```js
const { phone, password } = ctx.validate...

// 这样会不会很奇怪
const { value: { phone, password }} = ctx.validate...
```

**Comment by liuxiaodong** [comment]
这是为了和 Joi 返回数据保持一致。

**Comment by seekcx** [comment]
其实在 egg 的机制下可以做一些变通。或者遵循 egg 的一些规范。

比如：

![image](https://user-images.githubusercontent.com/8244814/40574673-c7343bfc-6108-11e8-8428-b4ccd77d881b.png)

app 下的挂的 joi，不一定非要大写，其它的挂载基本都遵循这个。
